### ISSUE TITLE
configInput.json ? 

### ISSUE THREAD

**Issue by Draym** [LeNiglo/TinyTank#1]
Mais où est il ? D:

**Comment by SwiTool** [comment]
J'ai une ancienne version de tinytank sur mon pc je regarderai si il y a ce fichier ^.^

**Comment by SwiTool** [comment]
En date du 17/06/2015
```json
{
  "MOVE_UP" : "W",
  "MOVE_DOWN" : "S",
  "MOVE_LEFT" : "A",
  "MOVE_RIGHT" : "D",
  "PUT_OBJECT": "B",
  "SHOOT" : "MOUSE_LEFT_BUTTON",
  "SPELL" : "MOUSE_RIGHT_BUTTON",
  "ESCAPE" : "ESCAPE"
}
```

**Comment by Draym** [comment]
c'est ça normalement, essaies de le push. il est pas sur le dépôt

**Comment by LeNiglo** [comment]
Faut pas le push. Il est différent sur chaque pc. Copie-Colle le

**Comment by Draym** [comment]
wtf on était con.. on aurait put faire un truc pour changer les input

**Comment by LeNiglo** [comment]
Oui, mais ça ne change pas que c'est un fichier de conf, donc gitignore.

**Comment by Draym** [comment]
tu gitignore pas un fichier de conf indispensable au jeu... faut mettre des touches de base

**Comment by Draym** [comment]
surtout que sans ça compile pas donc bon

**Comment by Draym** [comment]
bon bah j'ai pas réussi à relancer le jeu :D l'écran de connexion tout ça, les serveurs, beaucoup trop compliqué.. tu as down le site et le mainServ ?

faudrait que je retrouve les id du cheat admin et localhost dans le code

**Comment by LeNiglo** [comment]
Oui je crois que c'est down, en effet.
